### ISSUE TITLE
deserialize from Json string to Message object

### ISSUE THREAD

**Issue by hamata5656** [line/line-bot-sdk-java#100]
I want to deserialize from Json string to Message object, but is there something better?

**Comment by be-hase** [comment]
How about this ?
We support JSON-deserialize by Jackson.
( https://github.com/FasterXML/jackson )

```java
final ObjectMapper objectMapper = new ObjectMapper();
final CallbackRequest callbackRequest = objectMapper.readValue(json, CallbackRequest.class);
```

ref:
https://github.com/line/line-bot-sdk-java/blob/master/line-bot-servlet/src/main/java/com/linecorp/bot/servlet/LineBotCallbackRequestParser.java

**Comment by hamata5656** [comment]
Can not deserialize.
```java
String json = "{\"type\":\"text\",\"text\":\"Hello, world\"}";
final ObjectMapper objectMapper = new ObjectMapper();
final Message message = objectMapper.readValue(json, Message.class);
```

 
```java
	
 com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" (class com.linecorp.bot.model.message.TextMessage), not marked as ignorable (one known property: "text"])
 at [Source: {"type":"text","text":"Hello, world"}; line: 1, column: 38] (through reference chain: com.linecorp.bot.model.message.TextMessage["type"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
 	  …
 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
 ```



I can now deserialize by adding the following constructor to the TextMessage class.
```java
	@JsonCreator
	public TextMessage(@JsonProperty("text") String text) {
		this.text = text;
	}
```

**Comment by kazuki-ma** [comment]
@hamata5656 
Need some custom configuration.
Could you refer https://github.com/line/line-bot-sdk-java/blob/master/line-bot-servlet/src/main/java/com/linecorp/bot/servlet/LineBotCallbackRequestParser.java#L95-L101 ?

**Comment by kazuki-ma** [comment]
Oh sorry, you want to deserialize serialized Message JSON.. Please forget my comment.

Could you tell me why you want to create deserialized `Message` string?
For push/reply message, using `LineMessagingClient` is better.

**Comment by hamata5656** [comment]
Reply is done using LineMessagingClient.
However, since I want to manage the message to reply in one table, I want to keep it as a JSON String.

**Comment by kazuki-ma** [comment]
Thank you your feedback.

I was thinking about your case, but it is not easy to provide `Message` JSON serialize&deserialize feature, especially with compatibility consideration.

I'll try to support serialize&deserialization in SDK.

But please consider creating your own serialize/deserialize converter, to manage serialization SPEC.

**Comment by hamata5656** [comment]
Thank you for your reply.
I'll create my own serialize / deserialize converter.

**Comment by kazuki-ma** [comment]
Thank you.
