### ISSUE TITLE
[BUG] LineBlobClient UnauthorizedException response

### ISSUE THREAD

**Issue by sjpark-dev** [line/line-bot-sdk-java#1026]
## Bug Report

**Describe the bug**
I got an UnauthorizedException using LineBlobClient, and a 200 using LineMessagingClient.
Both used the same access token.
I am using com.linecorp.bot:line-bot-api-client:6.0.0
Is there a clue on why this happened?

**To Reproduce**

This issue was observed once, and I couldn't reproduce it.

**Comment by sjpark-dev** [comment]
This is the project i'm using.
<img width="1165" alt="image" src="https://github.com/line/line-bot-sdk-java/assets/66653739/2c15f2a8-145e-45b9-a7fc-cc35527da95d">

The issued occured using the `getMessageContent` method in LineBlobClient.

The message of the exception thrown was in the format below.

`java.util.concurrent.ExecutionException: com.linecorp.bot.client.exception.UnauthorizedException: Authentication failed. Confirm that the access token in the authorization header is valid. : ErrorResponse(requestId={requestId}, message=Authentication failed. Confirm that the access token in the authorization header is valid., details=[])`

**Comment by tokuhirom** [comment]
ah, sorry. i got it. i saw the source code of the version 7.x. yep. version 6.x contains `UnauthorizedException`.
and so, LineBlobClient is the independent object of the LineMessagingClient. You may need to check the object construction  process of the `LineBlobClient`.

**Comment by sjpark-dev** [comment]
```
LineBlobClient client = LineBlobClient
          .builder({accessToken})
          .build();
```

This is the way i construct the blob client.
I don't think the construction process is the problem.
I am managing many line official accounts, and this problem only occurs from a specific account.
I check the validity of the access token using the api, and it's valid.

Is it possilbe that the getContent API needs a specific permission and the access token lacks it?

**Comment by tokuhirom** [comment]
i don't have any ideas for this issue.
There may have been a problem with the communication path (proxy server, etc.).

By the way, if my understanding is correct, this issue is not depends on this SDK.

**Comment by sjpark-dev** [comment]
I understand, thank you for the support :)
One last question, is there a contact point that you recommend so that i can address this issue to Line?
