### ISSUE TITLE
[Question] Line stickers

### ISSUE THREAD

**Issue by mankicho** [line/line-bot-sdk-java#1066]
## Feature Request
Is there a way to get the url of line free stickers??

If I can get the url of the sticker with the id value, is it okay to use it? Are there any copyright issues?

**Comment by Yang-33** [comment]
> Is there a way to get the url of line free stickers??

I think there is no API to get free stickers and no automated solution, but there is a definition page https://developers.line.biz/en/docs/messaging-api/sticker-list/#sticker-definitions .

> If I can get the url of the sticker with the id value, is it okay to use it? Are there any copyright issues?

Please ask your question in LINE official account manager page! We're sorry developer don't know copyright issue.
