### ISSUE TITLE
[Question] version 6.x End of Life Date

### ISSUE THREAD

**Issue by sjpark-dev** [line/line-bot-sdk-java#1083]
According to README.md, the end of life date of version 6.x is November 18, 2023.
Does this mean I can't install the library from the Maven Central Repository and use it in my service after this date?

**Comment by Yang-33** [comment]
Thank you for using line-bot-sdk-java.

According to https://github.com/line/line-bot-sdk-java#sdk-lifecycle-documentation, 

> "End of Life Date" indicates when the version will no longer be supported.

No, you can install/download the old library but we won't support this after the date.
