### ISSUE TITLE
[Question] version 6.x End of Life Date continued

### ISSUE THREAD

**Issue by sjpark-dev** [line/line-bot-sdk-java#1085]
Thank you for using line-bot-sdk-java.

According to https://github.com/line/line-bot-sdk-java#sdk-lifecycle-documentation, 

> "End of Life Date" indicates when the version will no longer be supported.

So answer is ->  you can install/download the old library but we won't support this after the date.

_Originally posted by @Yang-33 in https://github.com/line/line-bot-sdk-java/issues/1083#issuecomment-1746276450_
            
Just to be clear, tell me if I understood you right.
Even after the end of life date, I will still be able to install/download the 6.x version SDK.
But there won't be updates on the 6.x version SDK.

**Comment by Yang-33** [comment]
Yes

**Comment by sjpark-dev** [comment]
ok thanks
