### ISSUE TITLE
Please annotate field @Nullable or @NotNull

### ISSUE THREAD

**Issue by smallufo** [line/line-bot-sdk-java#1144]
For package `com.linecorp.bot.messaging.model` 
Please annotate field `@Nullable` or `@NotNull`
At least let developers know what can be blindly fill null.

Or create builder like v6
![F-aS44kbkAAv_sQ](https://github.com/line/line-bot-sdk-java/assets/626659/5b11a7fe-a713-4dce-a055-fd53608dc93f)
![F-aVkprbAAA6IMP](https://github.com/line/line-bot-sdk-java/assets/626659/cb78f6c5-b91f-472e-a887-c641fd6e3ffc)

The coding style is so terrible. I totally don't know if it will work.
(A kotlin wrapper with default parameters is more welcome)

**Comment by tokuhirom** [comment]
I proposed #1145 , how do you feel this?

**Comment by smallufo** [comment]
Thanks , it looks good. But I still hope for NotNull and Nullable annotation.
BTW , it seems there was no ImageSize enum (like v6 https://github.com/tokuhirom/line-bot-sdk-java/blob/33a7eb4982fc3559b2c3b64b0af2363260b43397/line-bot-model/src/main/java/com/linecorp/bot/model/message/flex/component/Image.java#L51-L73C9 ) 
Is it intentional ?

**Comment by smallufo** [comment]
Some suggestion : 
A builder should provide safely object creation. It should not produce non-runnable code at COMPILE time.
Take `FlexButton.Builder` for example  ( [code here](https://github.com/line/line-bot-sdk-java/blob/85f5804f9cf0b88c818ef4c4692f16addfaae05a/clients/line-bot-messaging-api-client/src/main/java/com/linecorp/bot/messaging/model/FlexButton.java#L241-L242) )   It will finally check [if it has an action  defined](https://github.com/line/line-bot-sdk-java/blob/85f5804f9cf0b88c818ef4c4692f16addfaae05a/clients/line-bot-messaging-api-client/src/main/java/com/linecorp/bot/messaging/model/FlexButton.java#L318-L325 ) .

 It means the problem will only occur at runtime!

Since `Action` is the only required component inside `FlexButton` , The FlexButton.Builder's constructor should accept only one `Action` object instead of an empty constructor.

This ensures developers will not write non-runnable code at compile time.

This principal should be applied to other component's builders.

Thanks

**Comment by tokuhirom** [comment]
OK, I implemented the required parameters to the constructor of the Builder class. 
https://github.com/line/line-bot-sdk-java/pull/1147

@Nullable/@NotNull annotation is bit complex operation. We will do that in future release.

**Comment by smallufo** [comment]
Thanks, it's very helpful.
I am a little concerned.
Take [AreaTile](https://github.com/tokuhirom/line-bot-sdk-java/blob/0f815120125125b8b1397a35dc1e133f36b6751d/clients/line-bot-insight-client/src/main/java/com/linecorp/bot/insight/model/AreaTile.java#L38-L56) for example  . Does it mean it can accept either area or percentage (or both) ? which means if (area != null &&  percentage == null ) ,there will be NO exception thrown at runtime ?

I hope this is the desired behavior . Thanks.

**Comment by tokuhirom** [comment]
To clarify, AreaTile is a model object that's designed for responses. Consequently, you won't need to construct an AreaTile object yourself. The documentation at [here](https://developers.line.biz/en/reference/messaging-api/#get-demographic) doesn't explicitly specify whether both the area and percentage parameters are mandatory. It's my assumption that both of the parameters are typically filled.

For the sake of consistency, we provide Builders for all model objects, with careful deliberation regarding mandatory parameters for Requests. However, please note that we do not plan to provide such scrupulous details for models used for Responses.

**Comment by smallufo** [comment]
Thank you . I cannot wait to code with the builder.

**Comment by Yang-33** [comment]
https://github.com/line/line-bot-sdk-java/releases/tag/7.10.0 has this feature~
