### ISSUE TITLE
how do i multiple ReplyMessage in java?

### ISSUE THREAD

**Issue by TitusEfferian** [line/line-bot-sdk-java#117]
how do i multiple ReplyMessage in java?

**Comment by kazuki-ma** [comment]
To return multiple message, please return `List<Message>` on `@EventMapping` annotated method.

**Comment by krrrr38** [comment]
`ReplyMessage` contains 2 kinds of constructor. one is `new ReplyMessage(String replyToken, Message message)`, second one is `new ReplyMessage(String replyToken, List<Message> messages)`.
you can send multiple messages in a reply using second one.

**Comment by TitusEfferian** [comment]
![1496938271142](https://user-images.githubusercontent.com/27436728/26939036-39842e3e-4ca0-11e7-955d-82ebcd36907d.jpg)

where did i go wrong? 
sorry for disturbing your time

**Comment by krrrr38** [comment]
try this.
```java
List<Message> messages = Arrays.asList(new TextMessage("hai"), new TextMessage("how are you"));
LineMessagingServiceBuilder.create(lChannelAccessToken)
                           .build()
                           .replyMessage(new ReplyMessage(replyToken, messages))
                           .execute();
```

**Comment by TitusEfferian** [comment]
![messageimage_1496985299846](https://user-images.githubusercontent.com/27436728/26962019-73c91196-4d0d-11e7-9079-3db2d0b56c6e.jpg)
solved... thanks a lot
