### ISSUE TITLE
handleLocation error

### ISSUE THREAD

**Issue by morizooo** [line/line-bot-sdk-java#12]
In sample-spring-boot-kitchensink

When I send Location message from my phone, NullPointerException was occured.
Beause callback text is null and Not allowed null.

https://github.com/line/line-bot-sdk-java/blob/master/line-bot-api-client/src/main/java/com/linecorp/bot/client/DefaultLineBotClient.java#L273

**Comment by tokuhirom** [comment]
It's fixed by v2 release
