### ISSUE TITLE
LineMessagingClient.getProfile() does not work when MessageEvent.source is GroupSource

### ISSUE THREAD

**Issue by slux83** [line/line-bot-sdk-java#120]
Hi,

I have a bot which is present in a group with several users. I noticed that when I receive a MessageEvent the source is either GroupSource (when the messages is sent in the group itself) or UserSource when the bot receives a private message.

**Example of NON working profile retrieval sending a message in the group**
`event: MessageEvent(replyToken=xxxxx, source=GroupSource(groupId=zzzzz, userId=yyyyy), message=TextMessageContent(id=6412615796056, text=test), timestamp=2017-07-19T14:29:23.066Z)`
LOG: https://pastebin.com/raw/1jCn327t

**Example of working profile retrieval, sending a private message to the BOT**
`event: MessageEvent(replyToken=YYYYYYYYYYYYYYYYY, source=UserSource(userId=XXXXXXXXXXXX), message=TextMessageContent(id=6401892239567, text=test), timestamp=2017-07-17T12:52:22.607Z)`
LOG: https://pastebin.com/raw/psEH54xx

In both cases I retrive the profile in the following way:
```
CompletableFuture<UserProfileResponse> userProfileFuture = lineMessagingClient.getProfile(event.getSource().getUserId());

UserProfileResponse userProfile = null;
try {
	userProfile = userProfileFuture.get();
	System.out.println("Got user profile: " + userProfile.getDisplayName() + " ("+ userProfile.getUserId() + ")");
} catch (Exception e) {
	System.err.println("Cannot retrieve profile for user: " + e.getMessage());
}
```

**Comment by kazuki-ma** [comment]
Thank you for your feedback.

Getting profile of user who don't follow your bot is not supported now.
But we make this case supported just today.

We will update documents & SDKs soon.

**Comment by kazuki-ma** [comment]
@slux83 

Now `getGroupMembersIds(String groupId, String start);` method is available.
You can get group member profile even if he/she is not friend of BOT.

**Comment by slux83** [comment]
Sounds good! Thank you! Is the version already available on Maven repository? If so, which one is that?

**Comment by kazuki-ma** [comment]
@slux83 It is already available on released version.

Please refer `CompletableFuture<UserProfileResponse> getGroupMemberProfile(String groupId, String userId);` https://github.com/line/line-bot-sdk-java/blob/master/line-bot-api-client/src/main/java/com/linecorp/bot/client/LineMessagingClient.java#L91 and related methods.
