### ISSUE TITLE
[Feature Request] Disable the logger "com.linecorp.bot.client.wire"

### ISSUE THREAD

**Issue by caoPhoenix** [line/line-bot-sdk-java#1222]
How to disable the logger which is created in ApiClientBuilder? 

When I am using the MessagingApiClient class, there are some sensitive information in the request content that I do not want to appear in my service logs.

```java
private static Interceptor buildLoggingInterceptor() {
    final Logger slf4jLogger = LoggerFactory.getLogger("com.linecorp.bot.client.wire");

    return new HttpLoggingInterceptor(slf4jLogger::info)
            .setLevel(Level.BODY);
}
```

**Comment by tokuhirom** [comment]
To disable or modify the logging for the ApiClientBuilder or MessagingApiClient in your Java application, you can adjust the settings in your Logback configuration. This approach allows you to control the log output for these specific classes without affecting the logging behavior of the rest of your application.

for example:

```
<configuration>
    <logger name="com.linecorp.bot.client.wire" level="WARN"/>
</configuration>
```
