### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by Sarehu** [line/line-bot-sdk-java#137]
## Do this before creating an issue

- Check the [FAQ](https://github.com/line/line-bot-faq) for LINE bots
- Make sure your issue is **related to** the LINE Bot SDK. For general questions or issues about LINE bots, create an issue on the [FAQ](https://github.com/line/line-bot-faq) repository. Note that we don't provide technical support.

## When creating an issue

- Provide detailed information about the issue you had with the SDK
- Provide logs if possible

**Comment by Sarehu** [comment]
Bye

**Comment by Sarehu** [comment]
Bot bye

**Comment by Sarehu** [comment]
Autocancel:on

**Comment by Sarehu** [comment]
Autocancel:on

**Comment by Sarehu** [comment]
Autojoin:on

**Comment by kazuki-ma** [comment]
@Sarehu Sorry but you are testing in public area and we catching many notifications.
Please do not use this PR for your testing.
