### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by paulinaops** [line/line-bot-sdk-java#139]
I deployed the app to Heroku, provided the required details, but this shows up when I try to access the app:

> Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Tue Oct 10 09:40:17 UTC 2017
> There was an unexpected error (type=Not Found, status=404).
> No message available

Thanks for your help.

**Comment by krrrr38** [comment]
What application do you deployed?
If you deployed https://github.com/line/line-bot-sdk-java/tree/master/sample-spring-boot-echo, there is no endpoint except `POST /callback`, which is used for messaging api webhook.
