### ISSUE TITLE
Authorisation process in web-view renders 'invalid replyToken'

### ISSUE THREAD

**Issue by thepriteshsoni** [line/line-bot-sdk-java#151]
The replyToken becomes invalid after 10 seconds. I am trying to implement 3rd party authorisation using Line Messaging API. I have created a bot named 'Active Banking' which opens up a web view for authorisation.
By the time user credentials are entered in the webview and the login button is clicked, the replyToken for the passed query expires and 'invalid reply token' gets logged in the console.
Is there a possibility to extend the expiry time of a replyToken in Line?

**Comment by tokuhirom** [comment]
ReplyToken is a token for replying message from the user.
It's not avalavle for authentication.
If you want to provide an authentication feature, I recommend to use LINE web login instead.

**Comment by thepriteshsoni** [comment]
Thanks for the reply.
I have created a Line bot which acts as an intermediary between banking server and Line user.
A login template opens up a web-view in which user enters the username and password.
By the time the authentication is successful in the web-view and the response gets rendered, the replyToken becomes invalid.
As a result, the response from the bank server or the webhook URL doesn't reach the user because of token expiry.
![line replytoken](https://user-images.githubusercontent.com/30101184/32321593-9b6a8ade-bfe7-11e7-8d36-8fcc3678a187.png)

**Comment by tokuhirom** [comment]
Ah, I see. But the replyToken is a token for the short response message. If you want  to send a message after 10+ secs, you need to use Push message instead.

**Comment by thepriteshsoni** [comment]
Oh great!
Thanks a lot for the generosity, really appreciate it!

**Comment by thepriteshsoni** [comment]
For sending a PUSH message, the request body should contain two entities:
a. to -> the receiver ID
b. messages -> the array of message objects

Can you please tell me where can I find the receiver ID, as it is different from the Line ID?

**Comment by kazuki-ma** [comment]
Sorry but you are right. `receiver user ID` described this document is NOT equal to LINE ID.
The ID is starting `"U"` or `"u"` and follow 32 digits hex string.
You can get receiver ID via message event web hook or LINE Login.
