### ISSUE TITLE
How to write Rest Handler in sample-spring-boot-kitchensink

### ISSUE THREAD

**Issue by xvjiarui** [line/line-bot-sdk-java#154]
I am learning how to use line message api in java spring framework. 
- Is there any sample code about how to create a Rest Handler just like [KitchenSinkController annotated with LineMessageHandler](https://github.com/line/line-bot-sdk-java/blob/master/sample-spring-boot-kitchensink/src/main/java/com/example/bot/spring/KitchenSinkController.java), which could handle incomming http request?
The function I would like to make is sending push message to all users once the app received HTTP requests.

Many thanks!

**Comment by kazuki-ma** [comment]
You may need standard rest controller annotated Spring's `@RestController` instead of `@LineMessageHandler` like that.


```java
package com.example.bot.spring.echo;

import java.util.List;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.linecorp.bot.client.LineMessagingClient;
import com.linecorp.bot.model.Multicast;
import com.linecorp.bot.model.message.Message;

@RestController
public class BroadcastController {
    @Autowired
    LineMessagingClient client;

    @RequestMapping("/invoke_broadcast")
    public void invoke_broadcast() {
        Set<String> userIds = ;
        List<Message> messages = ;
        client.multicast(new Multicast(userIds, messages));
    }
}
```

Please note you need collecting userId of "all users" first. (via follow event webhook or something)
Simple API to push message to all users is not provided.

**Comment by xvjiarui** [comment]
Many thx, figured it out. 
Closing this issue.
