### ISSUE TITLE
User ID

### ISSUE THREAD

**Issue by paulinaops** [line/line-bot-sdk-java#155]
is there a way to get the User ID aside from webhooks?
i am using the API to send push messages to clients. can they find their User ID for their own record?

**Comment by tokuhirom** [comment]
You can get it from line web-login.

**Comment by paulinaops** [comment]
is that the same as the console?

**Comment by tokuhirom** [comment]
We don't provide any console to get the user ID.

**Comment by paulinaops** [comment]
i mean the developers console? is it the same as line web-login?

**Comment by tokuhirom** [comment]
There is no developers console site around LINE's platform, yet.
But you can build your own website to get your own user ID using LINE Login...
https://developers.line.me/en/docs/line-login/overview/

**Comment by paulinaops** [comment]
oh okay.. so there's no way for my clients to get their own user id except for line login?

**Comment by tokuhirom** [comment]
yep. There's only webhook or line login.

**Comment by paulinaops** [comment]
hello again, is it possible to get the user ID via LINE ID in the webhooks? like map the LINE ID to the user ID?

**Comment by ralphlai** [comment]
Hi @tokuhirom ,

I follow the doc and then create two app( LINE login app and LINE Message app )
I found that the cahnnel Id of these apps are different.

If I got userId by login app and webhook from ONE user,
are those userIds the same??

If not,
is there any way to know the userIds are belong to ONE user?
