### ISSUE TITLE
How to get user locale in messaging api

### ISSUE THREAD

**Issue by dheerajjoshim** [line/line-bot-sdk-java#158]
I am trying to use line messaging api to build some bots.
How to retrieve the user locale from user profiles?

I don't see any api definition in the documents. Does it even supported? or default is English?

**Comment by tokuhirom** [comment]
Currently, the LINE Messaging API does not provide user language information.
Bot developers seem to be developing different bots for different languages.

**Comment by dheerajjoshim** [comment]
Is there a plan to support this? In your road map?

**Comment by GuitarSucks** [comment]
Hi @dheerajjoshim 
Unfortunately its not in the road map at the moment. We will consider this feature on future releases.
