### ISSUE TITLE
Authentication line bot users using oauth

### ISSUE THREAD

**Issue by dheerajjoshim** [line/line-bot-sdk-java#160]
I figured out line doesn't support account linking at the moment.

So what is the suggested way of authenticating line bot users? I am looking at a way to map userId with the oauth tokens.?

I am planning to send the auth url to user and let them go to authentication website, once they are authenticated i need map line user Id to oauth.

**Comment by kazuki-ma** [comment]
>suggested way of authenticating line bot users? 

best way is using line login.
user id gotten by line login is the same of userId from webhook.

**Comment by dheerajjoshim** [comment]
What is the recommended approach, if I already have a authentication server. and my bot wants to authenticate the users but some how I need to map the line userId to authentication user

**Comment by dheerajjoshim** [comment]
Imagine a case where our customers already have an authentication mechanism and if they want to use it to authenticate the line user what is the recommended solution?

**Comment by namhoaingo** [comment]
@dheerajjoshim You got a good point here. I am in the same situation now. We have our own authentication system and have our own login credential. Now the question is how I can link the line id with our customer credential for message.

**Comment by dheerajjoshim** [comment]
@namhoaingo  What approach are you planning to take?

**Comment by tokuhirom** [comment]
New LINE Login was released. You can use account linking with OAuth2.
