### ISSUE TITLE
user history bot

### ISSUE THREAD

**Issue by yassineamira007** [line/line-bot-sdk-java#161]
well i want to know if is there any code to have conversation history ?

**Comment by tokuhirom** [comment]
I can't understand what you want to do.

**Comment by yassineamira007** [comment]
Well i wan't to now the histoiry of all the conversation message sended and  recieved on a Line bot

**Comment by kazuki-ma** [comment]
sorry, there is no way to get conversion history.
If you need the history, you need prepare webhook to store conversion histories.
