### ISSUE TITLE
can i connect to line bot without  handler.path ?

### ISSUE THREAD

**Issue by yassineamira007** [line/line-bot-sdk-java#164]
can i connect to my linebot with only by using channel-token and channel-secret without the handler.path ?

channel-token: 'Put Your Channel Token Here.'
channel-secret: 'Put Your Channel Secret Here.'
handler.path: /callback

**Comment by kazuki-ma** [comment]
Yes. `handler.path` has a default value `/callback`.
If you don't specify the value, default value will be used.

**Comment by yassineamira007** [comment]
well i'm using this webhookURL https://bots.dialogflow.com/line/c9d365a6-0f70-4ff6-8e78-4cf55d7542b5/webhook so what should i change the handler.path ?

**Comment by kazuki-ma** [comment]
If your LINE Bot don't need webhook (= notifications when user sent message) and dialogflow handles webhook instead, please leave `handler.path` as-is~.

Because I'm not familiar with dialogflow, if you need more information,
please describe your detail architecture.

**Comment by tokuhirom** [comment]
Since there is no answer, I will close this issue.
If you need support, please open a new issue.
