### ISSUE TITLE
User Id from LINE login and message app

### ISSUE THREAD

**Issue by ralphlai** [line/line-bot-sdk-java#167]
Hi 

I follow the doc and then create two app( LINE login app and LINE Message app )
I found that the cahnnel Id of these apps are different.

If I get userId by login app and webhook from **ONE** user,
are those userIds the same??

If not,
is there any way to know the userIds are belong to ONE user?

**Comment by tokuhirom** [comment]
If the same provider provides channels, userId from LINE Login and userId from LINE Messaging API are same.
