### ISSUE TITLE
Rich menu api usage

### ISSUE THREAD

**Issue by ralphlai** [line/line-bot-sdk-java#171]
Hi,

Is it possible that creating a richmenu and display to every user by default?
What I mean is like LINE Manager platform (https://admin-official.line.me), creating a rich menu and set "Display". Every user can see it immediately.
Seems that I must have to link menu to user first.

Another question, I do not see any update api of  rich menu. Is it possible to update rich menu after creating?

**Comment by kazuki-ma** [comment]
@ralphlai . Thank you for your feedback.
Let me move this question to https://github.com/line/line-platform-feedback/issues/57.
Please follow it.
