### ISSUE TITLE
Push Massege shoh 'to' invalid

### ISSUE THREAD

**Issue by RizkaOMG** [line/line-bot-sdk-java#176]
I used PHP to push massege line but show bad request like 400 {"message":"The property, 'to', in the request body is invalid (line: -, column: -)"}. 

I used code like this
```
$httpClient = new \LINE\LINEBot\HTTPClient\CurlHTTPClient('<channel access token>');
$bot = new \LINE\LINEBot($httpClient, ['channelSecret' => '<channel secret>']);

$textMessageBuilder = new \LINE\LINEBot\MessageBuilder\TextMessageBuilder('hello');
$response = $bot->pushMessage('+628123456789', $textMessageBuilder);

echo $response->getHTTPStatus() . ' ' . $response->getRawBody();
```
Is it wrong in phone number ?

Please help, Thanks.

**Comment by kazuki-ma** [comment]
pushMessage parameter `to` should be `userId`, not raw phone number.
You can find `userId` in message event received. (or LINE Login).

**Comment by RizkaOMG** [comment]
It user ID from Line Developer not LINE APP, right ?
It's possible to send push message with phone number ?

**Comment by kazuki-ma** [comment]
> It user ID from Line Developer not LINE APP, right ?
yes. you are right.

>It's possible to send push message with phone number ?
sorry it is impossible..
