### ISSUE TITLE
How to use Line emojis unicode in LINE API ?

### ISSUE THREAD

**Issue by rupam-debnath** [line/line-bot-sdk-java#179]
let's say I want to use this emoticon 0x100078, how to do that in JAVA?
Referring this doc on Line emojis, I am setting up emojis as responses to certain Line messages.
https://developers.line.me/media/messaging-api/emoji-list.pdf

In order to send a mixed text and emoji response, how should I convert the 0x100078 emoji code so that it is rendered properly on the Line chat interface?

**Comment by kazuki-ma** [comment]
Sorry, it isn't clear now.

`0x100078` is unicode codepoint of 'surrogate'.

There are no simple way to write like `\u0123` but you can select one of following

```java
emoji = new StringBuilder().appendCodePoint(0x100078).toString();
// or
emoji = String.copyValueOf(Character.toChars(0x100078));
```

**Comment by rupam-debnath** [comment]
hi, thank you for responding.
Your code helped a lot.
However, I need a little more help, as currently in the code that you specified, the codePoint value passed is an int value. But, in our backend the value is retrieved as a String.
On parsing it as an integer, I am encountering NumberFormatException because of the char 'x' in the string "0x100078".
Hard coding the int argument works correctly in the appendCodePoint, but the value being supplied is a String, and not an int.
Can you help?

**Comment by kazuki-ma** [comment]
You can use [Integer#decode](https://docs.oracle.com/javase/9/docs/api/java/lang/Integer.html#decode-java.lang.String-) ([ja](https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Integer.html#decode-java.lang.String-)) to convert from `0x` style hex string to `int`.

So you can write

```java
emoji = String.valueOf(Character.toChars(Integer.decode("0x100078")));
```

( general java question but welcome :-) )

**Comment by rupam-debnath** [comment]
Works like a charm... Thanks a lot! :D
