### ISSUE TITLE
ForbiddenException - Cannot use getGroupMembersIds()

### ISSUE THREAD

**Issue by slux83** [line/line-bot-sdk-java#180]
Hi,
in my Bot I wanted to use the getGroupMembersIds() to get the user IDs of members in a group where my bot is and also all the users. After giving a test I got the following Exception:

`com.linecorp.bot.client.exception.ForbiddenException: Access to this API is not available for your account, ErrorResponse(message=Access to this API is not available for your account, details=[])`

I also checked the LINE website and in order to have this API working I need to have a verified account. However the account only works for few Asian countries. Is there any way to achieve that?

Thanks

**Comment by KosukeKamiya** [comment]
Hi @slux83 ,

> Is there any way to achieve that?

Unfortunately, there is no way at this point to use this API in the region that verified accounts are not provided.
