### ISSUE TITLE
cant compile in line-bot-sdk-java

### ISSUE THREAD

**Issue by twappleon** [line/line-bot-sdk-java#186]
The SDK use lombok for value object
But the object implement some interface and those class didn't implement those method from interface
So compile report below error:
Error:(31, 8) java: com.linecorp.bot.model.event.UnknownEvent is not abstract and does not override abstract method getTimestamp() in com.linecorp.bot.model.event.Event

How can I fixed this issue,thanks

**Comment by leon456** [comment]
The issue I've solved

But I encounter another issue

I can find below class  in source code 

import com.linecorp.bot.model.richmenu.RichMenuIdResponse;
import com.linecorp.bot.model.richmenu.RichMenuListResponse;
import com.linecorp.bot.model.richmenu.RichMenuResponse;

But IDE tell me 

`Error:(27, 39) java: cannot find symbol
  symbol:   class RichMenuListResponse
  location: package com.linecorp.bot.model.richmenu`

I don't know why?

**Comment by twappleon** [comment]
The issue I've solved

But I encounter another issue

I can find below class in source code

import com.linecorp.bot.model.richmenu.RichMenuIdResponse;
import com.linecorp.bot.model.richmenu.RichMenuListResponse;
import com.linecorp.bot.model.richmenu.RichMenuResponse;

But IDE tell me

Error:(27, 39) java: cannot find symbol symbol: class RichMenuListResponse location: package com.linecorp.bot.model.richmenu

I don't know why?

**Comment by kazuki-ma** [comment]
It may be your development environment (IDE) issue.

How about searching `<your ide name> lombok cannot find symbol symbol`

And make sure you are already clean all caches.
If you use IntellJ, Files > Invalidate Caches&Restart may help you.
