### ISSUE TITLE
How to retrieve image sent by user ?

### ISSUE THREAD

**Issue by misaeljonathann** [line/line-bot-sdk-java#192]
Hi, i'm currently trying to get image that sent by user and use the image for another purpose.
Line dev provide this code for image message, and it said the binary image data is saved on the last line (files.copy).

#######################
```
final LineMessagingClient client = LineMessagingClient
        .builder("<channel access token>")
        .build();

final MessageContentResponse messageContentResponse;
try {
    messageContentResponse = client.getMessageContent("<messageId>").get();
} catch (InterruptedException | ExecutionException e) {
    e.printStackTrace();
    return;
}
Files.copy(messageContentResponse.getStream(),
           Files.createTempFile("foo", "bar"));
```
########################

so, how to retrieve the image that copied by the Files ?
and what does the foo/bar mean anyway ? is it a directory ?

and one more thing, how to reply back the user by using the image that sent by the user (same image) using code above ? i only know the method imagemessage that use URL as it's param, but the Files.copy code above doesnt produce any url.

sorry for my bad english.

**Comment by realr3fo** [comment]
You can review it the kitchensink code, the code  saved the user's image into a temporary file in the root folder, Correct me if I wrong
thanks.

**Comment by kazuki-ma** [comment]
`Files.createTempFile("foo", "bar")` means create temporary files with `foo` prefix and `bar` suffix under default temporary folder.
In this case, the returned value should be saved as a variable & you can use it.

Like following code.

```java
Path fileFromUser = Files.createTempFile("foo", "bar");
Files.copy(messageContentResponse.getStream(),
           fileFromUser);

somethingToDoFor(fileFromUser)
```
