### ISSUE TITLE
How to write Tests for handleImage, handleVideo, and handleAudio

### ISSUE THREAD

**Issue by realr3fo** [line/line-bot-sdk-java#193]
I am a bit confused on how to write the JUnit tests for handleImage, handleVideo, or HandleAudio. This is because we can't treat it like handleText where the text is already included in TextMessageContent. I haven't found any source on the web, can someone give me a hint or a code on how do I test the code?

**Comment by kazuki-ma** [comment]
The best way to test your method under integration with a 3rd-party library, you should create stub implementation. There are many moking(implemnting stub) support library.

I think major two library are [Mockit](http://site.mockito.org/) and [JMockit](http://jmockit.github.io/). 

This SDK also uses Mockit for test like https://github.com/line/line-bot-sdk-java/blob/master/line-bot-spring-boot/src/test/java/com/linecorp/bot/spring/boot/support/LineMessageHandlerSupportTest.java


JFYI
