### ISSUE TITLE
"Deploy to Heroku" button returns error during build, build fails and project cannot be created.

### ISSUE THREAD

**Issue by niconicosette** [line/line-bot-sdk-java#207]
Create a new channel in the LINE console using the instructions in the developer documentation, and then hit "Deploy to Heroku" in this project's ReadMe to try and deploy a sample bot. This does not work and returns the error:

```
 > Task :line-bot-cli:bootRepackage FAILED
       
       FAILURE: Build failed with an exception.
       
       * What went wrong:
       Execution failed for task ':line-bot-cli:bootRepackage'.
       > src/main/resources/launch.script (No such file or directory)
       
       * Try:
       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
       
       * Get more help at https://help.gradle.org
       
       Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
       See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings
       
       BUILD FAILED in 1m 35s
       31 actionable tasks: 31 executed
 !     ERROR: Failed to run Gradle!
       We're sorry this build is failing. If you can't find the issue in application
       code, please submit a ticket so we can help: https://help.heroku.com
       You can also try reverting to the previous version of the buildpack by running:
       $ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-gradle#previous-version
       
       Thanks,
       Heroku
 !     Push rejected, failed to compile Gradle app.
 !     Push failed
```

The build fails and the project cannot be created. The user receives the warning:

`There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.`

**Comment by kazuki-ma** [comment]
Sorry for inconvenience.  Let me check.

**Comment by kazuki-ma** [comment]
@niconicosette 

I fixed the problem which occurs `> src/main/resources/launch.script (No such file or directory)`.
Could you retry it?

**Comment by niconicosette** [comment]
Hi, thank you for the response!

Building the app works now, however, the echobot itself does not seem to work. Either there is a missing step in the instructions under "Deploy the "echo" sample bot" (https://developers.line.me/en/docs/messaging-api/building-sample-bot-with-heroku)

Or there is something amiss in the echobot code? It simply responds with the auto-message. When I disable the auto-message and greetings, the bot reads the messages but does not respond at all.

**Comment by kazuki-ma** [comment]
nnn. Let me check. Thank you.

**Comment by kazuki-ma** [comment]
Sorry I found the bug in master branch and now fixed.
I confirmed that issue is fixed on master.

Could you re-try now?

**Comment by niconicosette** [comment]
It's working now! Thank you.
