### ISSUE TITLE
Where is the Message Class?

### ISSUE THREAD

**Issue by nemu626** [line/line-bot-sdk-java#21]
I Can't import Message Class at model.callback package.Where is it?
> import com.linecorp.bot.model.callback.Message;

line-bot-spring-bootのREADMEに書かれているサンプルコードを書いてみたところ、Messageクラスが見つかりませんでした。

**Comment by synk** [comment]
Thank you for reporting. It was renamed to `Event` at 0.2.0.
We will fix the doc.
