### ISSUE TITLE
No "Events" Model for array of webhook Events

### ISSUE THREAD

**Issue by awharkrider** [line/line-bot-sdk-java#264]
## No "Events" Model for array of webhook Events
The [API Referance ](https://developers.line.me/en/reference/messaging-api/#request-headers) indicates that a webhook event will have a request body with an "Array of webhook event objects" but the SDK doesn't have a model to represent this. 

## Lack of Events Model
Since there was no model to format the request as an array of events I ended up writing my own. 
```
/**
 * Events object which contains the array of webhook event objects.
 * This object will be the json request body for webhook requests.
 */
public class LineEventsDTO {
    
    private final List<LineMessageEventDTO> events;
    
    /**
     * Get the webhook events.
     */
    public List<LineMessageEventDTO> getEvents() {
        return events;
    }
    
    @JsonCreator
    public LineEventsDTO(List<LineMessageEventDTO> events) {
        this.events = events;
    }
}
```

I only needed the MessageEvent (which I had to write my own for the indicated reason in issue https://github.com/line/line-bot-sdk-java/issues/263).
A better implementation would be to use a generic. 

**Example using a generic:**
```
/**
 * Events object which contains the array of webhook event objects.
 * This object will be the json request body for webhook requests.
 */
public class Events {
    
    private final List<T extends Event> events;
    
    /**
     * Get the webhook events.
     */
    public List<T extends Event> getEvents() {
        return events;
    }
    
    @JsonCreator
    public Events(List<T extends Event> events) {
        this.events = events;
    }
}
```

**Comment by kazuki-ma** [comment]
Thank you for your feedback.

In this SDK, the class you mentioned is called [CallbackRequest](https://github.com/line/line-bot-sdk-java/blob/master/line-bot-model/src/main/java/com/linecorp/bot/model/event/CallbackRequest.java).
