### ISSUE TITLE
Missing Line User ID (human readable) in UserProfileResponse

### ISSUE THREAD

**Issue by slux83** [line/line-bot-sdk-java#266]
Hi,

when I retrive the `UserProfileResponse `from the `LineMessagingClient `I noticed that I only get the following information:

- Display name: the current display name of the user (e.g. "slux83 long name")
- User Long ID: this is the long version of the user ID (e.g. UA8B1FEF42B2C0330094A69979070E2B5)
- Picture URL
- Status message

What is missing is the unique Line user ID that is used to add friends. 

Is there a way to retrieve it? 
I could not find anything in the rest api https://developers.line.me/en/reference/social-api/#get-user-profile

Thanks

**Comment by wiradikusuma** [comment]
I read it somewhere, users' LINE ID is not sent for privacy reasons.

What you have is a company-scoped id (the "long id" you mentioned). Which means—I haven't tested this—you can create another bot under the same company account and send message to users of your previous bot, although you should probably ask user for permission.

**Comment by kazuki-ma** [comment]
@slux83 thank you for your question. @wiradikusuma thank you answering.

As @wiradikusuma is answered, ew think `User ID for add friends` is privacy information and should not be exposed in UserProfileResponsefrom.

**Comment by slux83** [comment]
Ok thank you for the clarification, it makes sense.
