### ISSUE TITLE
User mention message support

### ISSUE THREAD

**Issue by slux83** [line/line-bot-sdk-java#269]
Hi,

usually with Line is possible to tag people by using the `@DisplayName` feature. Does the SDK support anything such this? Since I can retrieve the user display name, would be nice to just add a '@' at the beginning to tag him/her so that they will receive a notification.

Thanks

**Comment by imasahiro** [comment]
Add reference to feedback issue. https://github.com/line/line-platform-feedback/issues/122

**Comment by tokuhirom** [comment]
Sorry, this is an issue tracker of the LINE Messaging API SDK.

Please try to use our forum.
https://www.line-community.me/questions
