### ISSUE TITLE
Is handleTextMessageEvent(...) called synchronously?

### ISSUE THREAD

**Issue by slux83** [line/line-bot-sdk-java#275]
Hi,
what's the way messages are dispatched to my Spring Boot application event mapping handler?
```
@SpringBootApplication
@LineMessageHandler
public class MyBotApplication {
    @EventMapping
    public TextMessage handleTextMessageEvent(MessageEvent<TextMessageContent> event) {
        // Is this called synchronously?
    }
}
```

Can I assume that the ```handleTextMessageEvent(...)``` is called sinchronously passing messages in a serialized way or it can be called in a multi-threading way?

Thanks.

**Comment by kazuki-ma** [comment]
There are not SPEC, but in current implementation.

* Event dispatcher is called synchronously(sequentially) for one event callback.
* In case next event callback is reached during old callback is processing, this is handled by another thread and concurrently processed.


Just interested: Do you interested asynchronous/parallel processing?

**Comment by slux83** [comment]
Thank you very much. I just wanted to know if I have to protect my internal structures from potential concurrent access when users send "commands" to my bot.
