### ISSUE TITLE
is there any API callback that can return who has read the previous message by sending a command?

### ISSUE THREAD

**Issue by rainerregan** [line/line-bot-sdk-java#276]
Hi all,

I currently working with line messaging API, is there any API callback that can return who has read the previous message by sending a command?

Thank you for all of your contributions.

**Comment by tokuhirom** [comment]
There's no support for LINE Messaging API yet.

**Comment by rainerregan** [comment]
I saw a bot that can do that thing, it can reply to users who have read the message, and display their name, what possibly can make it happend?

**Comment by slux83** [comment]
> I saw a bot that can do that thing, it can reply to users who have read the message, and display their name, what possibly can make it happend?

It's probably an unofficial Bot like few I saw that they are normal users with just a client and some code behind. As I know, those are not "legal" meaning that they could get banned eventually

**Comment by rainerregan** [comment]
Okay then, thank you very much for all of your contributions.
