### ISSUE TITLE
Update spring-boot 2.0 as default

### ISSUE THREAD

**Issue by kazuki-ma** [line/line-bot-sdk-java#279]
Use spring-boot 2.0 as default dependency.
And optionally add compatibility test for spring-boot 1.x.

1.x is not active version and some users want to use line-bot-sdk-java with 2.x and got unexpected results. like https://github.com/line/line-bot-sdk-java/issues/277

**Comment by imasahiro** [comment]
Fixed via https://github.com/line/line-bot-sdk-java/pull/280
