### ISSUE TITLE
Image aspectRatio now supports freeform 

### ISSUE THREAD

**Issue by thibbs** [line/line-bot-sdk-java#304]
https://github.com/line/line-bot-sdk-java/blob/45acb06f962ea148a352699b9d5b921e449cf6c8/line-bot-model/src/main/java/com/linecorp/bot/model/message/flex/component/Image.java#L64-L89

As of latest API reference: https://developers.line.biz/en/reference/messaging-api/#f-image Image aspectRatio now follows {width}:{height} format.

From the API reference:
Aspect ratio of the image. Specify in the ```{width}:{height}``` format. Specify the value of the ```{width}``` property and the ```{height}``` property in the range from 1 to 100000. However, you cannot set the ```{height}``` property to a value that is more than three times the value of the ```{width}``` property. The default value is ```1:1```.

**Comment by imasahiro** [comment]
Thanks for report. https://github.com/line/line-bot-sdk-java/pull/303 should fix this issue.

**Comment by imasahiro** [comment]
Close via #303
