### ISSUE TITLE
NPE thrown by LineMessageHandlerSupport:183

### ISSUE THREAD

**Issue by mrexmelle** [line/line-bot-sdk-java#310]
## Background
We encounter a lot of `NullPointerException` (NPE) logback error message in our monitoring system that leads to `LineMessageHandlerSupport:183`.

## Solution
A check should be done to see whether the thrown `InvocationTargetException` instance has `cause` or not. If `InvocationTargetException::getCause` returns `null`, the `log.error` function should print the exception information instead of its cause.

## Attachment
A log is attached to show the frequency of the error since the service is opened for public.
<img width="1003" alt="linemessagehandlersupport_183" src="https://user-images.githubusercontent.com/6904811/52773601-f6b2eb00-306d-11e9-8cdf-aa314a358f19.png">

**Comment by imasahiro** [comment]
Close via #311
