### ISSUE TITLE
This compilation unit is not on the build path of a Java project

### ISSUE THREAD

**Issue by FLOODY88** [line/line-bot-sdk-java#316]
So I just started using this SDK. First of all: As seen in the docs, I apparently need to clone the whole rep to use e.g. the echo class. Is that so or is there any other way to use this SDK? Basiclly, I want to create my own LINE bot to listen for chat messages.

However, I tried started using it with Heroku. I cloned the rep to Eclipse and I can commit it just fine to Heroku but when I am trying to edit something, it tells me "This compilation unit is not on the build path of a Java project". Furthermore, I also receive this message:

![issue](https://i.imgur.com/c0Ae8cC.png "Issue")

I tried editing the `EchoApplication`. So, is there a way to use this SDK in my own project and use all it's features? I tried adding the JARs to my build path, but eventually that did not work either.

**Comment by tokuhirom** [comment]
The issue is around your Eclipse configuration, not this SDK.
