### ISSUE TITLE
LINE Bot callback exception: Invalid API signature

### ISSUE THREAD

**Issue by FLOODY88** [line/line-bot-sdk-java#317]
I just set up my project and started by pasting the sample echo code to my application to verify, that everything works properly. However, I run into the issue that I get the error `LINE Bot callback exception: Invalid API signature` everytime I send my bot a message, thus I don't receive any reply.

I am kind of new to spring boot, so I do not know much about this. Sorry, if this questions is kind of obvious but I did not find any solution that solved my problem. The wiki did not help either.

I am using Maven and Heroku.

```java
@SpringBootApplication
@LineMessageHandler
@RequestMapping("/callback")
public class EchoTest {
    
    public static void main(String[] args) {
	SpringApplication.run(EchoTest.class, args);
    }

    @EventMapping
    public TextMessage handleTextMessageEvent(MessageEvent<TextMessageContent> event) {
	return new TextMessage("Echo: " + event.getMessage().getText());
    }
}
```

**Comment by imasahiro** [comment]
@FLOODY88 Hi, I think, you don't need to apply `@RequestMapping("/callback")` since line-bot-spring-boot add mapping to `/callback` and it wires the events to your `EchoTest.handleTextMessageEvent`.

**Comment by FLOODY88** [comment]
> @FLOODY88 Hi, I think, you don't need to apply `@RequestMapping("/callback")` since line-bot-spring-boot add mapping to `/callback` and it wires the events to your `EchoTest.handleTextMessageEvent`.

Hi @imasahiro, thanks for your reply! Adding only `@RequestMapping` will result in the same error `c.l.b.s.b.i.LineBotServerInterceptor     : LINE Bot callback exception: Invalid API signature`. Thus, no echo reply.

However, the error only appears after sending the second message. No error on the first message, but also no reply. Any ideas?

**Comment by FLOODY88** [comment]
Somehow my channel was broken, created a new one and tried it with the new secret and token and it worked. Sorry for the inconvience.
