### ISSUE TITLE
Ver 2.5.0 has not published

### ISSUE THREAD

**Issue by micheam** [line/line-bot-sdk-java#335]
Version 2.5.0 has specified on 118f05c , but it seems not published on maven repository.
https://mvnrepository.com/artifact/com.linecorp.bot/line-bot-api-client

Do you plan to publish this version ?

(We want to use new feature about Rich menu api #324)

**Comment by imasahiro** [comment]
Oops, sorry for that. Let me deploy 2.6.0 today (instead of 2.5.0).

**Comment by imasahiro** [comment]
Changed my mind. I release 2.5.0 and deploy it to maven central.  Please check https://github.com/line/line-bot-sdk-java/releases/tag/2.5.0 Note that, it might take some time to reflect the release to central.
