### ISSUE TITLE
Push Images don't appear on both desktopand android

### ISSUE THREAD

**Issue by Ourobolost** [line/line-bot-sdk-java#339]
I use push api to send Image Message to followers the images land well on only iphone but desktop and android version is not able to view or download image

**Comment by imasahiro** [comment]
Hi, sorry for late response. I would like to know following things for check.  Could you check followings please?
* Which version of line-bot-sdk-java are you using?
* Is it possible to provide minimal reproducer code?

**Comment by imasahiro** [comment]
Let me close due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
