### ISSUE TITLE
[Feature Request] can we add duration to AudioMessageContent ?

### ISSUE THREAD

**Issue by spotby** [line/line-bot-sdk-java#348]
Hi All, is it possible to add duration to the AudioMessageContent pojo? I can't seem to find a way to get the duration on my webhooks.

**Comment by spotby** [comment]
Here is a PR with duration added #

**Comment by imasahiro** [comment]
Thanks for filing issue and PR. Maybe I forgot to sync newly added field. let me check your PR.

**Comment by imasahiro** [comment]
Close via #350
