### ISSUE TITLE
RFC: Support Multi Bot Hosting. (minor?)

### ISSUE THREAD

**Issue by kazuki-ma** [line/line-bot-sdk-java#36]
Currently, some bot parameter like `channel-secret` is global configuration and it is not a list.
We can't host multiple bot in same JVM/Spring's Application Context.

**Comment by tokuhirom** [comment]
We should support it. Or, add document about this  issue.

**Comment by kazuki-ma** [comment]
https://github.com/line/line-bot-sdk-java/pull/107 is in progress.

**Comment by imasahiro** [comment]
Currently, there is no plan to support such a feature since we would like to focus on providing a single bot hosting.
