### ISSUE TITLE
Can I  link lin(b) url in URIAction?

### ISSUE THREAD

**Issue by rudeo512** [line/line-bot-sdk-java#370]
I'm upgrading from 2.4 version to 3.0 version. Because I needs FlexPosition in Text of FlexComponent

I noticed that URIAction no longer supports the LINE URL scheme. 
Is there a way to use LINE URL schem in URIAction?

**Comment by kazuki-ma** [comment]
@rudeo512 Thank you for your reporting.
Can you provide a error message?

**Comment by rudeo512** [comment]
I can push message with null at altUri in URIAction.
I sorry for being annoying.

**Comment by kazuki-ma** [comment]
OK. Thank you for your feedback. :-)
