### ISSUE TITLE
[Feature Request] API endpoint that returns information about how users interact with broadcast messages sent from your LINE official account.

### ISSUE THREAD

**Issue by kazuki-ma** [line/line-bot-sdk-java#378]
> LINE Developers We've added a new Messaging API endpoint that returns information about how users interact with broadcast messages sent from your LINE official account.
> For more information, see https://developers.line.biz/en/news/

**Comment by tkgauri** [comment]
- [ ] [Get user interaction statistics](https://developers.line.biz/en/reference/messaging-api/#get-message-event)

**Comment by tkgauri** [comment]
Can be implemented after this pr is merged: https://github.com/line/line-bot-sdk-java/pull/388

**Comment by tokuhirom** [comment]
#388 was already implemented. I'll try this issue.
