### ISSUE TITLE
Get ID of user from group chat.

### ISSUE THREAD

**Issue by timgshi** [line/line-bot-sdk-java#40]
When receiving a message from a room, only the room ID is given as the source of the message. How do I look up the user ID of the sender?

**Comment by tokuhirom** [comment]
LINE Messaging API doesn't provide user ID for each message, sent in group or room.
Java SDK can't provide it. And we don't have any plan to provide it now.

**Comment by hckrmoon** [comment]
is there any issues with it ? I just wanna know why not. even though there are much more things we can do If user id provided.

**Comment by kumai** [comment]
@hckrmoon  Because we care about user's privacy. User in a group is not always a user who has agreed to provide his/her ID to you. We know the inconvenience you said. Unfortunately we won't show you any specific plan about it for now, but we are working on it.

**Comment by hckrmoon** [comment]
Now I got it ! Thanks @kumai

**Comment by Calvinn097** [comment]
what if provide a fake id, but is unique for each user on the group where the bot is on. so with group_id and that group's user unique id we can explore more

**Comment by slux83** [comment]
I agree with what Calvinn said. Should not be hard to create a mask and give a unique User ID which is not the original one.

**Comment by kiennatibula** [comment]
Hi where I can get the group id in line using PHP ?
