### ISSUE TITLE
[BUG] The api url of getting messages and followers is incorrect in LineMessagingService 

### ISSUE THREAD

**Issue by gokenpei** [line/line-bot-sdk-java#419]
## Bug Report

**Describe the bug**
When I call the function getNumberOfMessageDeliveries or getNumberOfFollowers, I get the IllegalArgumentException (URL query string "date={date}" must not have replace block. For dynamic query parameters use @Query)

The URL path defined in LineMessagingService is 
@GET("v2/bot/insight/followers?date={date}")
Should this be changed to
@GET("v2/bot/insight/followers")

**Comment by kazuki-ma** [comment]
@gokenpei thank you for your reporting.
We will check and fix soon.
