### ISSUE TITLE
[BUG]The enum of status for NumberOfMessagesResponse is incorrect

### ISSUE THREAD

**Issue by gokenpei** [line/line-bot-sdk-java#420]
## Bug Report

**Describe the bug**
When I call getNumberOf{SentReply|SentPush|SentMulticast}Messages, I will get a GeneralLineMessagingException (String "unready": not one of the values accepted for Enum class: [OutOfService, Unready, Ready])

**Comment by kazuki-ma** [comment]
will be fixed also with https://github.com/line/line-bot-sdk-java/issues/419. Thank you.

**Comment by kazuki-ma** [comment]
Thank you. We will release the fix in this week.
