### ISSUE TITLE
New property added to "sticker message" webhook event

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-java#425]
> We added a new stickerResourceType property to the webhook event that notifies you when a sticker message is sent.
> Use this property to see what type of sticker was sent (still image, animated sticker, sticker with sound, etc.).

Messaging api reference for [`sticker`](https://developers.line.biz/en/reference/messaging-api/#wh-sticker)
[News](https://developers.line.biz/en/news/2019/12/05/add-stickerresourcetype-property/)

**Comment by loda-kun** [comment]
@tkgauri  @kazuki-ma  This one seems suitable for me to dig in this repository, can I do this?

**Comment by kazuki-ma** [comment]
@loda-kun Of course, yes and sorry for waiting for you. Thank you for contributing.
