### ISSUE TITLE
Support stay event added to beacon event

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-java#427]
> In the Messaging API beacon event, a stay event has been added to indicate that the user is staying in the covered area of the beacon.

Messaging api reference: https://developers.line.biz/en/reference/messaging-api/#beacon-event
News: https://developers.line.biz/en/news/#a-stay-event-was-added-to-beacon-event-2019-12-06

**Comment by tokuhirom** [comment]
Beacon event's `type` parameter is mapped to the String field.  We don't need to change any code.

https://github.com/line/line-bot-sdk-java/blob/master/line-bot-model/src/main/java/com/linecorp/bot/model/event/beacon/BeaconContent.java#L34
