### ISSUE TITLE
[Feature Request] Version in bulid.gradle.

### ISSUE THREAD

**Issue by OzoraGoro** [line/line-bot-sdk-java#434]
Check the build.gradle.
The version is different.
It is written as 3.4.0.

tag:3.3.1

**Comment by kazuki-ma** [comment]
Thank you for your reporting. Could you check again?

Tag 3.3.1 is on 89f130335007fe743831acd334192fb6a9adf5f8.
And marked `version = '3.3.1'` on https://github.com/line/line-bot-sdk-java/blob/3.3.1/build.gradle#L51

![image](https://user-images.githubusercontent.com/1370068/72503484-291d2780-387f-11ea-86bb-792495b721c2.png)

**Comment by OzoraGoro** [comment]
Update has been confirmed.
Thank you.
