### ISSUE TITLE
[Feature Request] Maven cannot be used.

### ISSUE THREAD

**Issue by OzoraGoro** [line/line-bot-sdk-java#435]
Please register line-bot-parser 3.3.1 to maven.
There is a dependency and cannot be used.

**Comment by kazuki-ma** [comment]
Oh, sorry for your inconvenience. We are fixed it. Thank you!

https://repo1.maven.org/maven2/com/linecorp/bot/line-bot-parser/3.3.1/

**Comment by kazuki-ma** [comment]
Let me close the issue.

**Comment by OzoraGoro** [comment]
Waiting for reflection.
https://mvnrepository.com/artifact/com.linecorp.bot/line-bot-parser
![maven_repository](https://user-images.githubusercontent.com/59698066/72543259-cfd9e600-38c8-11ea-99bc-d3978b3a3edb.png)
