### ISSUE TITLE
[Feature Request] I found a gap between document and SDK.

### ISSUE THREAD

**Issue by yhtgogo** [line/line-bot-sdk-java#440]
## Feature Request
Thanks to you, I am using the SDK well.

I found a gap between document and SDK at imagemap action object - Messaging API.

Document has label property.
But SDK has not.

So, I request you to investigate the gap, please.

* Document : https://developers.line.biz/en/reference/messaging-api/#imagemap-action-objects
* URIImagemapAction : https://github.com/line/line-bot-sdk-java/blob/master/line-bot-model/src/main/java/com/linecorp/bot/model/message/imagemap/URIImagemapAction.java
* MessageImagemapAction : https://github.com/line/line-bot-sdk-java/blob/master/line-bot-model/src/main/java/com/linecorp/bot/model/message/imagemap/MessageImagemapAction.java

**Comment by kazuki-ma** [comment]
Thank you for your feedback & sorry for late reply.
You are right, we'll add this property in next release.
Thank you.
