### ISSUE TITLE
[Feature Request]Can this be integrated to WhatsApp for Business?

### ISSUE THREAD

**Issue by dosindi** [line/line-bot-sdk-java#462]
## Feature Request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by imasahiro** [comment]
> Can this be integrated to WhatsApp for Business? 

This repository only provides a SDK for LINE messaging API. So, this SDK only may help you to integrate LINE messaging API with your app but about WhatsApp part, you need to take care by yourself about how to intergate.

**Comment by imasahiro** [comment]
Since there is nothing I can help at the moment, let me close this ticket. 
@dosindi Please feel free to reopen with more information, thanks.
