### ISSUE TITLE
Creating an interactive session

### ISSUE THREAD

**Issue by thegalang** [line/line-bot-sdk-java#510]
Hello line developers

I am currently trying to develop a line chatbot for flashcards, and i need a way for the user the "interact" with the boot by text. That is, the bot could maintain some sort of state for where a user last accesses it. Something like this:

User: \addcard
Bot: front of card?
User: Mitocondria
Bot: back of card?
User: The power house of the cell
Bot: Card Mitocondria has been added!

i have read:
- https://developers.line.biz/
- https://developers.line.biz/en/news/
- https://developers.line.biz/en/services/messaging-api/

And looks like the only thing i found is single message commands. Is it possible to achieve this using spring-boot bot? Any helpful references and code snippets is also appreciated.

Also, sorry if i asked this in the wrong place.

**Comment by tokuhirom** [comment]
You can identify the user by userId. So, you can store the state using RDBMS or NoSQL.

**Comment by thegalang** [comment]
Ah, i thought of that solution.
Just thought that it would be really messy since there would be a lot of interactions.

A curious question: can the API handle multiple messageHandlers?

**Comment by imasahiro** [comment]
For such a case, you need to handle by yourself.

**Comment by thegalang** [comment]
alright, thanks
