### ISSUE TITLE
[Feature Request] Custom aspect ratio for Icon component

### ISSUE THREAD

**Issue by k3ntr** [line/line-bot-sdk-java#512]
## Feature Request

**Is your feature request related to a problem? Please describe.**

https://developers.line.biz/en/reference/messaging-api/#icon is saying about `aspectRatio` of `Icon` object like following:
> Aspect ratio of the icon. {width}:{height} format. The values of {width} and {height} must be in the range 1–100000. {height} can't be more than three times the value of {width}. The default value is 1:1.

However, the implementation accepts only major `aspectRatio`s

https://github.com/line/line-bot-sdk-java/blob/master/line-bot-model/src/main/java/com/linecorp/bot/model/message/flex/component/Icon.java
```
    public enum IconAspectRatio {
        @JsonProperty("1:1")
        R1TO1,
        @JsonProperty("2:1")
        R2TO1,
        @JsonProperty("3:1")
        R3TO1,
    }
```

This request is to handle all valid ratios.

**Describe the solution you'd like**

Its similar issues was resolved previously, so I expect we can resolve in a similar way.
https://github.com/line/line-bot-sdk-java/issues/304
https://github.com/line/line-bot-sdk-java/pull/303

**Additional context**

**Comment by tokuhirom** [comment]
Related news: https://developers.line.biz/en/news/2018/12/
