### ISSUE TITLE
[HELP] How to receive webhook event objects

### ISSUE THREAD

**Issue by natehsu** [line/line-bot-sdk-java#515]
## Feature Request
Hi,
I already run and test "sample-spring-boot-echo" with LINE OFFICIAL ACCOUNT successfully. Because I have different requirements, so I can't use "line-bot-spring-boot" library.

In my requirements, I need binding multiple message api channels to one webhook url, then programming dynamic switch channel token and channel secret with different LINE OFFICIAL ACCOUNT.

First step, I want programming receive webhook event objects, and get the destination channel ID. But I can't find sample code in line-bot-sdk-java project. Is there any sample code? My project build based on spring boot 2.

I would appreciate your help.

**Comment by kazuki-ma** [comment]
Thank you for your feedback.

You should following steps when you handle multiple events.

1. Get webhook payload by byte[].
2. Verify payload signature (with corresponding secret)
3. Parse byte[] as `CallbackRequest`
4. Get list of events.

Step2 & 3 is most difficult part of this, and follows may help.

https://github.com/line/line-bot-sdk-java/blob/master/line-bot-parser/src/main/java/com/linecorp/bot/parser/WebhookParser.java#L46-L73

**Comment by natehsu** [comment]
Thank you for your reply.

I follow step 1->2->3->4 then it works.
Count I change step to 1->3->2->4? 
Because I want to know sent to which channel, then use corresponding secret to verify payload signature.

And how could I use event destination field to identify api channel? Then I will use the channel secret to verify. For example log:
2020-05-08 15:00:03.932  INFO 26919 --- [https-jsse-nio-8443-exec-4] com.example.bot.spring.echo.Index        : callbackRequest: {"destination":"Ub00cbd0031af9c76b9af261f14b3dXXX","events":[{"type":"message","replyToken":"e3dc6f29060f4cc5a67a828d7b9c4265","source":{"type":"user","userId":"U47e722ceb4ad0e120dabaaeb79aXXXXX","senderId":"U47e722ceb4ad0e120dabaaeb79aXXXXX"},"message":{"type":"text","id":"11926810761XXX","text":"234"},"timestamp":{"nano":262000000,"epochSecond":1588921203},"mode":"active"}]}


I would appreciate your help.

**Comment by kazuki-ma** [comment]
You’re right, could you add bot identifier into path?

Like `/callback/{bot's channelId}` or `/callback?channelId=value`.

If you can do it, you can extract bot identifier and verify signature.

**Comment by natehsu** [comment]
Yes, good idea.

I already got correct channelId.

**Comment by natehsu** [comment]
Is there any sdk api for parsing all events to Java bean?

For example：
Message event data -> MessageEvent<TextMessageContent> event
Follow event data -> ...etc
Unfollow event data -> ...etc

I would appreciate your help.

**Comment by kazuki-ma** [comment]
There is no simple way. Please write if blocks like

```java
for (Event event : callbackRequest.getEvents()) {
    if (event instanceof MessageEvent) {
        MessageContent messageContent = ((MessageEvent) event).getMessage();
        if (messageContent instanceof TextMessageContent) {
            // Do something for message with text.
        }
    } else if (event instanceof LeaveEvent) {
        // Do something for Leave Event
    }
}
```

**Comment by natehsu** [comment]
It works!
Thank you very much.
