### ISSUE TITLE
Maven repository not update yet?

### ISSUE THREAD

**Issue by chegola** [line/line-bot-sdk-java#52]
@tokuhirom , I have navigated Maven repository (https://mvnrepository.com/artifact/com.linecorp.bot/line-bot-spring-boot/1.1.0)  then include the dependencies com.linecorp.bot:line-bot-spring-boot and all other com.linecorb.bot. I found that line-bot-spring-boot did not include some latest classes such as com.linecorp.bot.spring.boot.annotation.LineMessageHandler. 

Is there any chance to upload the latest classes to Maven repository?

**Comment by tokuhirom** [comment]
It's not available on maven central yet. I'll release it   next week.

**Comment by chegola** [comment]
Thank you very much @tokuhirom

**Comment by kazuki-ma** [comment]
@chegola 

Sorry please wait until next week.
But now, 1.2.0-SNAPSHOT is available. Please use if you can test SNAPSHOT. It includes `LineMessageHandler`

```java
<dependency>
  <groupId>com.linecorp.bot</groupId>
  <artifactId>line-bot-spring-boot</artifactId>
  <version>1.2.0-SNAPSHOT</version>
</dependency>
```

**Comment by chegola** [comment]
@kazuki-ma  Thanks you so much.

**Comment by chegola** [comment]
I'll close this issue

**Comment by kazuki-ma** [comment]
Version 1.2.0 is released in last week. 
Sorry for late updated. JFYI.

```xml
<dependency>
  <groupId>com.linecorp.bot</groupId>
  <artifactId>line-bot-spring-boot</artifactId>
  <version>1.2.0</version>
</dependency>
```
