### ISSUE TITLE
Messaging API - May 2020 update

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-java#521]
News: https://developers.line.biz/en/news/2020/05/12/messaging-api-update-may-2020/

- [x] Message character limit and media file usage conditions changed
- [x] [Get LINE emoji information from the text object of a webhook event](https://developers.line.biz/en/reference/messaging-api/#wh-text)
- [x] [Retry failed message](https://developers.line.biz/en/reference/messaging-api/#retry-api-request)

**Comment by imasahiro** [comment]
https://github.com/line/line-bot-sdk-java/pull/528

**Comment by tkgauri** [comment]
#534
