### ISSUE TITLE
incorrect wording (blog)

### ISSUE THREAD

**Issue by b41somp** [line/line-bot-sdk-java#526]
https://github.com/line/line-bot-sdk-java/blob/064988a60e1b4e1079a509f706e58cbb3ddb763a/line-bot-api-client/src/main/java/com/linecorp/bot/client/LineBlobClient.java#L24

**Comment by kazuki-ma** [comment]
@b41somp thank you for your reporting.
I'll fix the issue in https://github.com/line/line-bot-sdk-java/pull/527.
