### ISSUE TITLE
[Feature Request]Provide a way to specify channel token for each request

### ISSUE THREAD

**Issue by alex-lx** [line/line-bot-sdk-java#557]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We're developing an app for our customer to integrate their line account, of course, include the ability to send push message. For saving resources, we decide to share a `LineMessagingClient`, unfortunately, It seems there's no way to set a channel token for each request, so we request your guys to support this

**Describe the solution you'd like**
Add an overloaded method which has an additional `channelToken` argument for each request method such as `pushMessage`
**Describe alternatives you've considered**
1. Use `ThreadLocal` to store the current token and then read by a custom `ChannelTokenSupplier`, but it won't work because the thread which the client called is different from the thread `ChannelTokenSupplier.get()` called.
2. Create a `LineMessagingClient` for each `access token`, all the `LineMessagingClient`s share the same `OkHttpClient`'s connection pool and dispatcher by `OkHttpClient.newBuilder()`. It works (and is what we use now), however we think it might a little heavyweight because something could be shared.

**Additional context**
No

**Comment by alex-lx** [comment]
Gentle ask any guys on this issue😄

**Comment by tkgauri** [comment]
@alex-lx 
> For saving resources, we decide to share a LineMessagingClient,

Could you explain what do you mean by this?

**Comment by alex-lx** [comment]
Hi, @tkgauri I guess using a single `LineMessagingClient` instance may reduce some memory usage than using many `LineMessagingClient`s (as many as  `accessToken` count), and there would be thousands of line account in our system(I hope so😂), so it would be nice to let us just use one instance.

**Comment by imasahiro** [comment]
>  It works (and is what we use now), however we think it might a little heavyweight because something could be shared.

Just curious, could you point out what kind of things you think heavyweight and what kind of resources that can be shared?

**Comment by imasahiro** [comment]
Well, AFAIK and as you shared at description it is impossible to support per-request channel token by ChannelTokenSupplier (or okhttp/retrofit features (e.g. interceptors, call factory)) since real okhttp call is happened at different thread and okhttp's Request and Call are immutable.

Easiest way to address this is, forking retrofit interfaces (e.g. LineMessagingService) and add `@Header("Authorization") ` to each methods like following but I prefer not to apply this way to current retrofit interfaces since I think, it reduce usability.

```java
interface LineMessagingService {
    @POST("v2/bot/message/reply")
    Call<BotApiResponseBody> replyMessage(@Body ReplyMessage replyMessage,
                                          @Header("Authorization") String channelToken);
}
```

**Comment by alex-lx** [comment]
@imasahiro Thanks for your response. I'm not very familiar with `retrofit`, I guess the `retrofit` might not so lightweight(Tell me if I'm wrong😅), and creating a `retrofit` might be expensive(using a retrofit pool can be a workaround, however,😀😀 we're looking for something better 😀).

**Comment by tokuhirom** [comment]
i guess okhttp3 creates the dispatcher for each OkHttpClient for retrofit. maybe, it seems bit heavy operation since every OkHttpClient holds an ExecutorSerivce.

My suggestion is, create LIneMessagingServiceFactory. Please see the code below. @imasahiro 

https://github.com/line/line-bot-sdk-java/pull/561

**Comment by kazuki-ma** [comment]
@alex-lx 

Think you can use ThreadLocal but you should care about OkHttp's dispatching mechanism.

Follow is an example. you can modify the access token via ThreadLocal.

https://github.com/line/line-bot-sdk-java/compare/master...kazuki-ma:tokenViaThreadLocal?expand=1

Consideration
* If you are using ThreadLocal, take care about thread local leak / contamination. You need to make sure it's cleared after request.
* I confirmed manual method call is work but SDK's auto reply by handler method return value maybe not working.

**Comment by alex-lx** [comment]
@kazuki-ma Thanks so much, I'll take a look soon👍
