### ISSUE TITLE
Model VideoMessageContent not fit to the document

### ISSUE THREAD

**Issue by alex-lx** [line/line-bot-sdk-java#568]
Model in the SDK:
https://github.com/line/line-bot-sdk-java/blob/407d85eacca1a475599ecdd509f9a6c37e24c929/line-bot-model/src/main/java/com/linecorp/bot/model/event/message/VideoMessageContent.java#L32-L40
Model in the document:
https://developers.line.biz/en/reference/messaging-api/#wh-video
```
  {
    "id": "325708",
    "type": "video",
    "duration": 60000,
    "contentProvider": {
      "type": "external",
      "originalContentUrl": "https://example.com/original.mp4",
      "previewImageUrl": "https://example.com/preview.jpg"
    }
  }
```
In SDK, the model has no `duration` field and has one extra `url` field.

**Comment by tokuhirom** [comment]
The issue was introduced by this commit. https://github.com/line/line-bot-sdk-java/commit/51fb038ee64ce6a5961ba42a03e4f0b6b89c9049

**Comment by alex-lx** [comment]
Hi, @tokuhirom.

Would you mind to change the `duration` field type to `Integer` which is the `duration` type in `AudioMessageContent` class.

And, something not so related, using a number to represent duration is not clear which unit was used, think to change the field name to `durationMillis` or use `java.time.Duration` type would be better.

**Comment by tokuhirom** [comment]
ah. good catch. I changed the type to Integer.

**Comment by tokuhirom** [comment]
Duration support is a good idea, but there's nothing method like this in the sdk.... now.
maybe we can change the type at next major release :P

**Comment by alex-lx** [comment]
Got it, feel free to close this issue when resolved.
