### ISSUE TITLE
UnknownSource misses field type

### ISSUE THREAD

**Issue by electrobabe** [line/line-bot-sdk-java#58]
like for UnknownEvent

line-bot-api-client version 1.2.0

**Comment by tokuhirom** [comment]
What do you mean?

**Comment by electrobabe** [comment]
When I try to map the Json String to the CallbackRequest java class, I get the error: 

> com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" (class com.linecorp.bot.model.event.source.UserSource), not marked as ignorable (one known property: "userId"])
>  at [Source: {"events":[{"type":"message","replyToken":"82dce99766c64c44800ab4a5a346820f","source":{"userId":"U3eee52852c65d80f6d888695c6b76f6b","type":"user"},"timestamp":1489434877017,"message":{"type":"text","id":"5777707649369","text":"hi"}}]}; line: 1, column: 146] (through reference chain: com.linecorp.bot.model.event.CallbackRequest["events"]->java.util.ArrayList[0]->com.linecorp.bot.model.event.MessageEvent["source"]->com.linecorp.bot.model.event.source.UserSource["type"])

to reproduce this error use this test:

**Comment by electrobabe** [comment]
```
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.linecorp.bot.model.event.CallbackRequest;
import org.junit.Test;

import static org.fest.assertions.Assertions.assertThat;

public class LineAPITest {
    @Test
    public void getEvents() throws Exception {

        String json = "{\"events\":[{\"type\":\"message\",\"replyToken\":\"82dce99766c64c44800ab4a5a346820f\",\"source\":{\"userId\":\"U3eee52852c65d80f6d888695c6b76f6b\",\"type\":\"user\"},\"timestamp\":1489434877017,\"message\":{\"type\":\"text\",\"id\":\"5777707649369\",\"text\":\"hi\"}}]}";
        
        ObjectMapper m = new ObjectMapper();
        m.configure(JsonParser.Feature.ALLOW_UNQUOTED_CONTROL_CHARS, true);
        CallbackRequest req = m.readValue(json, CallbackRequest.class);
        assertThat(req).isNotNull();
    }
}
```

**Comment by electrobabe** [comment]
@tokuhirom if you have any questions, please feel free to contact me directly (didn't get the notifications)

**Comment by electrobabe** [comment]
@tokuhirom fails with 

```
<dependency>
  <groupId>com.linecorp.bot</groupId>
  <artifactId>line-bot-api-client</artifactId>
  <version>1.6.0</version>
</dependency>
```

**Comment by kazuki-ma** [comment]
@electrobabe 
There are some custom configuration is needed to deserialize event json into model.
Could you refer https://github.com/line/line-bot-sdk-java/blob/master/line-bot-servlet/src/main/java/com/linecorp/bot/servlet/LineBotCallbackRequestParser.java#L94-L102?

**Comment by electrobabe** [comment]
alright! it was simply the configuration of the ObjectMapper, that was missing:

`objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);`

BTW I don't use Spring Boot but Spring Web

**Comment by kazuki-ma** [comment]
I am happy that your issue solved. 👍
