### ISSUE TITLE
Are there any api to let user add friend?

### ISSUE THREAD

**Issue by Thaina** [line/line-bot-sdk-java#64]
I has a plan to make a service to find line friend. So I want to have some API to get a `userID` from mid so I can construct a link `line.me/ti/p/~userID`
But login API only give `displayname` and `mid`. And I can't find any api to retrieve `userID` from `mid` or access token

Is it possible or are there any alternative solution?
Such as a link format like `line.me/ti/m/~mid` that would redirect user who click a link to `line.me/ti/p/~userID`

Or an api that would let user send message to target user from his access token, so they could add each other?

**Comment by tokuhirom** [comment]
We will provide LINE login that provides LINE Messaging API compatible userId later.. But there's no way to convert mid and userId for now.

**Comment by Thaina** [comment]
@tokuhirom Thanks for your answer. How can I know when there will be new version of line login that would make it possible?

**Comment by tokuhirom** [comment]
We will provide new information on the line developers site.
https://developers.line.me/news

**Comment by Thaina** [comment]
Hello are there any update about this feature?
