### ISSUE TITLE
リッチメニューの作成時に、ユーザーIDがパラメータとして、指定できませんか？

### ISSUE THREAD

**Issue by shouaya** [line/line-bot-sdk-java#70]
例えば：
リッチメニュー→コンテンツ設定→リンク→URL→http://xxxx.com?uid={uid}

**Comment by tokuhirom** [comment]
Web ページ側で LINE Login でユーザー認証していただくのが良いかと思います。
User ID が取得可能な LINE Login が年内にリリース予定ですので、そちらご利用ください。
