### ISSUE TITLE
how to close web window by javascript

### ISSUE THREAD

**Issue by shouaya** [line/line-bot-sdk-java#71]
when i use urlaction open a url window page, however how can i close it with javascript.

such as -> javascript:window.close();

**Comment by tokuhirom** [comment]
what do you mean? i guess it doesn't related to line-bot-sdk-java.

**Comment by shouaya** [comment]
step1: i use sdk send a urlaction  such as http://xxxxx.com/demopage
step2: i resive this message on line app client
step3: i click the url and goto the demopage
step4: i click a finish button on demopage to close itself

->however i can not close it with javascript window.close();

**Comment by tokuhirom** [comment]
iOS's WebView and android's WebView denies `window.close()`. It's not a LINE app's issue.

**Comment by shouaya** [comment]
is there any solution to fix it
thank you for answer

**Comment by Thaina** [comment]
It is browser security standard that you can only close window that was opened with `window.open`. Open window from url cannot be closed

**Comment by shouaya** [comment]
if LINE support some open api like cordova may be can fix it
such as ->  javascript:line.dom.window.close();

**Comment by shouaya** [comment]
i find a solution to fix it:
⇒<a href="https://line.me/R/ti/p/%40klu5514s">閉じる</a>
※href=XXXX  ←this is your 友だち追加ボタンのURL
LINE@MANAGER ⇒アカウント設定⇒基本設定⇒友だち追加ボタン

**Comment by yueming-Chen** [comment]
how did you fixed this issue?
DId you operate DOM of Line?

**Comment by JangirPankaj** [comment]
window.close() is working fine on the IOS devices when you running a webview in the IOS. But it is not working on andorid.

**Comment by MiguelIgdalino** [comment]
Is there a solution for this on android?
