### ISSUE TITLE
Messaging API Update - November 2021

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-java#714]
News: https://developers.line.biz/en/news/2021/11/09/messaging-api-update/

- [x] [You can now retrieve the text entered by the user in a message sticker](https://developers.line.biz/en/news/2021/11/09/messaging-api-update/#messaging-api-202111-01)
- [x] [You can now retrieve up to 1000 user IDs of friends](https://developers.line.biz/en/news/2021/11/09/messaging-api-update/#messaging-api-202111-02)

**Comment by tokuhirom** [comment]
https://github.com/line/line-bot-sdk-java/blob/cbcb096023f2de84684751839656a0c458f6ee41/line-bot-model/src/main/java/com/linecorp/bot/model/event/message/StickerMessageContent.java

- [] Needs to add MESSAGE and CUSTOM to the enum StickerResourceType.
- [] Add text field to StrickerMessageContent

**Comment by tawAsh1** [comment]
#715 #716
