### ISSUE TITLE
Can I integrate line-bot-sdk-java without using spring-boot ?

### ISSUE THREAD

**Issue by pai911** [line/line-bot-sdk-java#77]
I am running my server with play framework.

In Play, there is already a way to route a URL to a function call, and get the data in the post body.

All I need is convert the json file to objects in **line-bot-model**

and use the **line-bot-api-client** to communicate with the client

Can I use line java bot sdk without spring-boot ?

If yes, is there any tutorial on how to do this ?

**Comment by tokuhirom** [comment]
We are supporting spring-boot and Java servlets.
But, line-bot-api-client and models are not depends on boot and servlets, you  can  use these modules with Play framework.

Sorry, there's no tutorial for using sdk with Play framework.

**Comment by pai911** [comment]
Thank you! I will try to integrate line-bot-api-client and models in Play server

Maybe after i succeeded I can contribute a integration tutorial to the community

**Comment by kazuki-ma** [comment]
Let me close this PR.
If you finish your integration. Please share. Thanks.
