### ISSUE TITLE
[Feature Request] Support for verifying the validity of short-lived and long-lived channel access tokens

### ISSUE THREAD

**Issue by sjpark-dev** [line/line-bot-sdk-java#773]
Hi, I was wondering why there is no support for the feature [verify the validity of short-lived and long-lived channel access tokens](https://developers.line.biz/en/reference/messaging-api/#verfiy-channel-access-token) in the LineOauthClient part of the sdk.

If possible, I would like to contribute by adding support for the feature.

Thanks.

**Comment by Yang-33** [comment]
will be implemented in https://github.com/line/line-bot-sdk-java/issues/947

**Comment by Yang-33** [comment]
You can use this feature from v7.0.0.
