### ISSUE TITLE
About the Event.getSource().getUserId() and mid retrieved from Line Login

### ISSUE THREAD

**Issue by pai911** [line/line-bot-sdk-java#81]
Hi! 

There seem to be two types of IDs for users on line's platform.

one is the userId in the messaging API, and another one is the mid received from Line login.

Why do you use different ID?

We are going to implement a LINE Bot, and we want to recognize the user (as someone on our website) when he adds our bot

So I tried to implement LINE login on our website. After the user login, his account will be saved in our user database (Now the LINE ID is mapped to a user on our website)

But I found that for the two APIs, the user's IDs are different.....

Is there any way that we can map the two different IDs?

**Comment by tokuhirom** [comment]
LINE Login's ID and LINE Messaging API's ID are incompatible.

(We will make these IDs compatible)

**Comment by pai911** [comment]
Glad that you put this in your plan. Look forward to this update, thank you

**Comment by GuitarSucks** [comment]
Ohh Sorry this issue is solved.
The latest LINE Login will now have the same ID.
