### ISSUE TITLE
Is there a way to have the timezone or the location of the user?

### ISSUE THREAD

**Issue by paulrouget** [line/line-bot-sdk-java#82]
The timestamp is not enough.

If the user sends a message like "book table at restaurant tomorrow", I don't know what "tomorrow" means without a timezone.

**Comment by kazuki-ma** [comment]
Sorry, there are no way to get user's timezone or location now.
I think your example is meaningful. let us take note for future improvement. Thanks for your feedback.

**Comment by kazuki-ma** [comment]
Feedback-ed to internal. Let me close it.
