### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by kristiantokarim** [line/line-bot-sdk-java#83]
is there a way to let users send their location ?

**Comment by kazuki-ma** [comment]
User can send location message by tapping "+" menu manually.
![line_p201717_161651](https://cloud.githubusercontent.com/assets/1370068/21740183/d194327e-d4f4-11e6-9f46-b76446edad51.jpg)

**Comment by kristiantokarim** [comment]
But, I don't see the + menu when I chat with account that using messaging API or official account. The "+" menu only appear when I chat with normal account ( my friends, groupchat, or multichat )

**Comment by kazuki-ma** [comment]
"+" menu in (some) official account's talk room is disabled. But messaging API's not.
If you are seeing "Menu" bar, please tap keyboard icon first.

![line_p201717_234940](https://cloud.githubusercontent.com/assets/1370068/21746957/5f677822-d59a-11e6-9a7e-28041963b857.jpg)

**Comment by kristiantokarim** [comment]
Can I create something like that menu bar that ask for user location ?

**Comment by kazuki-ma** [comment]
Sorry, there are no way to create custom UI to ask location.
(Menu bar customize nor by rich menu)

**Comment by kristiantokarim** [comment]
Okay thank you. I more question, is it possible to create a rich menu or custom UI for other task ? not for share location.

**Comment by kazuki-ma** [comment]
Current rich menu only supports

* Send fixed message text.
* Open web url.

for tap action.

Send location (or image/view etc...) is not supported now.

**Comment by kristiantokarim** [comment]
Oh okay thank you, may I know in what section I can see the rich menu tutorial in kitchensink ? I look for it but I can find it.

**Comment by kazuki-ma** [comment]
There are no section about rich menu in kitchensink sample.
Because rich menu is managed by CMS (https://admin-official.line.me), not a part of Messaging API.
Please check your cms.

![cd1dcdae94b66b0ac4330a7c0bbb60a5](https://cloud.githubusercontent.com/assets/1370068/21794468/e430b18c-d73d-11e6-9d65-c3b3aabc2cee.png)

**Comment by kristiantokarim** [comment]
Thank you so much. Have a nice day

**Comment by kazuki-ma** [comment]
@kristiantokarim 

Hello.

Although it has passed some time, we are publish line:// scheme SPECs.
Scheme `line://nv/location` opens the "Location" screen.

https://developers.line.me/en/docs/messaging-api/using-line-url-scheme/#opening-the-location-screen

Please refer it.

**Comment by kristiantokarim** [comment]
Hey, thanks for notifying me (:

Kristianto Karim
Student ID : 16514330 / 13514075
*School of Electrical Engineering and Informatics*
Bandung Institute of Technology

2017-11-28 10:15 GMT+07:00 kazuki-ma <notifications@github.com>:

**Comment by chingting** [comment]
@kazuki-ma if I want people to check-in in certain location, is it possible to restrict people to pin to other places? Otherwise they might cheat. Thank you!
