### ISSUE TITLE
[Feature Request] Support multiple bots in same line-bot-spring-boot backed project

### ISSUE THREAD

**Issue by jiangying000** [line/line-bot-sdk-java#917]
Now I can only start one bot in on spring boot project:
with one config:
```
# line
line.bot.channel-token=p...nyilFU=
line.bot.channel-secret=772bcfb2...8619c8f7f
line.bot.handler.path=/callback
```

Can I start multiple bots server for multiple bots in one spring boot project ?

**Comment by tokuhirom** [comment]
There's no plan to support it for now.
