### ISSUE TITLE
question: real length limit of a voice message?

### ISSUE THREAD

**Issue by jiangying000** [line/line-bot-sdk-java#918]
![image](https://user-images.githubusercontent.com/23182033/224603491-fbc06505-47da-4c0d-b994-baa0be46e860.png)
sdk said 60s

doc https://developers.line.biz/en/reference/messaging-api/#audio-message didn't mention it

![IMG_20230313_113528.jpg](https://user-images.githubusercontent.com/23182033/224602498-fba26f27-c1d0-4bee-87e3-be8ba8cc354b.jpg)
I tested as normal human user, sending successed with 78s voice

what's the real limitation ?

**Comment by tokuhirom** [comment]
Maybe the old version of the document says "less than 1 minute". But it was removed(I don't know why it's gone).
Documentation is always correct.

**Comment by jiangying000** [comment]
> Maybe the old version of the document says "less than 1 minute". But it was removed(I don't know why it's gone).
> Documentation is always correct.
> 

so there is actually no limitation on voice length given the file size compliant ?

**Comment by tokuhirom** [comment]
yep

**Comment by jiangying000** [comment]
thanks, fixed in #923
