### ISSUE TITLE
pushMessage() doesn't work inside thenAccept()

### ISSUE THREAD

**Issue by wiradikusuma** [line/line-bot-sdk-java#95]
I use Spring Boot. Using this code, the message arrives in target phone:

	line.pushMessage(new PushMessage("target", new TextMessage("bla")))

This code does not work (message does not arrive, no error):

	line.getMessageContent("valid-id").thenAccept(new Consumer<MessageContentResponse>() {
		void accept(MessageContentResponse response) {
			line.pushMessage(new PushMessage("target", new TextMessage("bla")))
		}
	})

Am I missing something?

**Comment by kazuki-ma** [comment]
Hello.
I can't reproduce your issue.

Could you check your wire log?
Because I want to know
* Is `getMessageContent` method successfully finished or not (Callback in `thenAccept` will be called or not)
* Even if `#pushMessage` method is called, there are any error response or not.

Please be careful, "message content id" has life time and will be expired after that time has passed from event is received. 

https://devdocs.line.me/en/#content
> Content is automatically deleted after a certain period from when the message was sent. There is no guarantee for how long content is stored.


## Codes used to repro. (But I can't repro)
```java
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.linecorp.bot.client.LineMessagingClient;
import com.linecorp.bot.model.PushMessage;
import com.linecorp.bot.model.event.MessageEvent;
import com.linecorp.bot.model.event.message.ImageMessageContent;
import com.linecorp.bot.model.message.TextMessage;
import com.linecorp.bot.spring.boot.annotation.EventMapping;
import com.linecorp.bot.spring.boot.annotation.LineMessageHandler;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@LineMessageHandler
@SpringBootApplication
@AllArgsConstructor
@Slf4j
public class Application {
    public static void main(final String... args) {
        SpringApplication.run(Application.class, args);
    }

    private final LineMessagingClient client;

    @EventMapping
    public TextMessage handleImageEvent(
            final MessageEvent<ImageMessageContent> event) {
        client.getMessageContent(event.getMessage().getId()).thenAccept(messageContentResponse -> {
            log.info("getMessageContent successfully finished.");

            final TextMessage message = new TextMessage("getMessageContent successfully finished. "
                                                        + messageContentResponse);

            client.pushMessage(new PushMessage(event.getSource().getSenderId(), message));
        });

        return new TextMessage("ImageMessageContent is alived. " + event);
    }
}
```

## Result
![repro](https://cloud.githubusercontent.com/assets/1370068/23606072/7dfdd544-02a2-11e7-856e-cd5e7575336b.jpg)

**Comment by wiradikusuma** [comment]
It's weird, your code works, but as soon as I convert to Groovy, it stops working. Nevermind, I'll just use Java for this part. Thanks!
