### ISSUE TITLE
Many errors after import and open the project

### ISSUE THREAD

**Issue by isdzulqor** [line/line-bot-sdk-java#98]
Hi, I've cloned and imported your project in my Intellij and I want to try to build the springboot sample app using this Line SDK. but I got some errors like this pic below. 
![selection_090](https://cloud.githubusercontent.com/assets/12388558/24250946/1d99c818-100b-11e7-99a0-1d2920b8351f.png)
I still wondering which part that makes error. I observe the CLASS that have VALUE annotation do not have  getter method. So, could you help me to figure out this problem, please? 
Thank you :)

**Comment by kazuki-ma** [comment]
This project uses [Lombok](https://projectlombok.org/) plugin which generates getter/setter and has many useful features.

If you are using IntelliJ, please try with [Lombok plugin for IntelliJ](https://plugins.jetbrains.com/plugin/6317-lombok-plugin).

(compiled code (*.jar) is completely standard class file. Project which depends this SDK doesn't need Lombok/Lombok plugins.)

**Comment by isdzulqor** [comment]
Okey, thank you for answering.
What about defining Dline.bot.channelSecret and Dline.bot.channelSecret manually, not generate using ./gradlew......... because I am using maven in my project.

**Comment by kazuki-ma** [comment]
@isdzulqor 

Configuration system of this SDK is based on spring-boot's way.
`./gradlew` with `-Dkey=vaue` is one of the way to setting configuration property.
See [Part IV. Spring Boot features - 24. Externalized Configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) for all ways to configuration.

Maybe the best way to setting configuration is create `application.yml` file in your `src/main/resources/config`.

```yml:application.yml
line:
  bot:
    channel-secret: secret
    channel-token: token
```

If your IntelliJ is configured collectedly, autocomplete is also available.
<img width="1114" alt="d45a2bb2dd2e263213e3dfc4685d396a" src="https://cloud.githubusercontent.com/assets/1370068/24305059/03f8d77e-10ff-11e7-8e2a-91a18f0d34a3.png">

**Comment by isdzulqor** [comment]
Okey thank you @kazuki-ma. Really helpful.

**Comment by isdzulqor** [comment]
I just try to build a new simple project using springboot. and then I copied KitchenSinkController from springboot sample app KitchenSinkController. and then I tested it to my bot. I deployed it to Heroku. after that I inputed my heroku's web url to my chatbot's webhook in Line Business Center.
but nothing worked. I still could not response from my chatbot. Could you help me to figure out this. Thank you

**Comment by isdzulqor** [comment]
I forgot to add /callback in my webhook url. Now it's been working. Thank you
